-- ============================================================================
-- IronFlow — Seed: muscles + 50 exercises
-- ============================================================================

-- Muscles
insert into public.muscles (slug, name, group_name) values
    ('chest',      'Chest',         'upper'),
    ('back',       'Back',          'upper'),
    ('lats',       'Lats',          'upper'),
    ('shoulders',  'Shoulders',     'upper'),
    ('biceps',     'Biceps',        'upper'),
    ('triceps',    'Triceps',       'upper'),
    ('forearms',   'Forearms',      'upper'),
    ('quads',      'Quadriceps',    'lower'),
    ('hamstrings', 'Hamstrings',    'lower'),
    ('glutes',     'Glutes',        'lower'),
    ('calves',     'Calves',        'lower'),
    ('abs',        'Abs',           'core'),
    ('obliques',   'Obliques',      'core'),
    ('lower_back', 'Lower Back',    'core'),
    ('cardio',     'Cardiovascular','cardio')
on conflict (slug) do nothing;

-- 50 exercises
with m as (select slug, id from public.muscles)
insert into public.exercises (slug, name, category, equipment, difficulty, primary_muscle_id, instructions) values
    ('barbell-bench-press',    'Barbell Bench Press',       'strength', 'barbell',    'intermediate', (select id from m where slug='chest'),      'Lie on bench, lower bar to chest, press up.'),
    ('incline-bench-press',    'Incline Bench Press',       'strength', 'barbell',    'intermediate', (select id from m where slug='chest'),      'Set bench to 30 deg, press bar from upper chest.'),
    ('dumbbell-fly',           'Dumbbell Fly',              'strength', 'dumbbell',   'beginner',     (select id from m where slug='chest'),      'Arc dumbbells with slight elbow bend.'),
    ('push-up',                'Push Up',                   'strength', 'bodyweight', 'beginner',     (select id from m where slug='chest'),      'Lower chest to floor, press up.'),
    ('dips',                   'Dips',                      'strength', 'bodyweight', 'intermediate', (select id from m where slug='triceps'),    'Lower until shoulders below elbows, press up.'),
    ('pull-up',                'Pull Up',                   'strength', 'bodyweight', 'intermediate', (select id from m where slug='lats'),       'Pull chin above bar, control descent.'),
    ('chin-up',                'Chin Up',                   'strength', 'bodyweight', 'intermediate', (select id from m where slug='biceps'),     'Supinated grip, pull chin above bar.'),
    ('lat-pulldown',           'Lat Pulldown',              'strength', 'machine',    'beginner',     (select id from m where slug='lats'),       'Pull bar to upper chest, squeeze lats.'),
    ('bent-over-row',          'Bent Over Barbell Row',     'strength', 'barbell',    'intermediate', (select id from m where slug='back'),       'Hinge hips, row bar to lower ribs.'),
    ('seated-cable-row',       'Seated Cable Row',          'strength', 'machine',    'beginner',     (select id from m where slug='back'),       'Row handle to abdomen, squeeze shoulder blades.'),
    ('deadlift',               'Deadlift',                  'strength', 'barbell',    'advanced',     (select id from m where slug='back'),       'Hinge, grip bar, drive floor away, lock out.'),
    ('romanian-deadlift',      'Romanian Deadlift',         'strength', 'barbell',    'intermediate', (select id from m where slug='hamstrings'), 'Hinge with soft knees, feel hamstring stretch.'),
    ('overhead-press',         'Overhead Press',            'strength', 'barbell',    'intermediate', (select id from m where slug='shoulders'),  'Press bar overhead from front rack.'),
    ('dumbbell-shoulder-press','Dumbbell Shoulder Press',   'strength', 'dumbbell',   'beginner',     (select id from m where slug='shoulders'),  'Press dumbbells overhead from shoulders.'),
    ('lateral-raise',          'Lateral Raise',             'strength', 'dumbbell',   'beginner',     (select id from m where slug='shoulders'),  'Raise arms out to shoulder height.'),
    ('face-pull',              'Face Pull',                 'strength', 'machine',    'beginner',     (select id from m where slug='shoulders'),  'Pull rope to face, external rotation.'),
    ('barbell-curl',           'Barbell Curl',              'strength', 'barbell',    'beginner',     (select id from m where slug='biceps'),     'Curl bar with elbows pinned.'),
    ('dumbbell-curl',          'Dumbbell Curl',             'strength', 'dumbbell',   'beginner',     (select id from m where slug='biceps'),     'Alternate arms, supinate at top.'),
    ('hammer-curl',            'Hammer Curl',               'strength', 'dumbbell',   'beginner',     (select id from m where slug='biceps'),     'Neutral grip curl for brachialis.'),
    ('tricep-pushdown',        'Tricep Pushdown',           'strength', 'machine',    'beginner',     (select id from m where slug='triceps'),    'Push rope/bar down, keep elbows fixed.'),
    ('skull-crusher',          'Skull Crusher',             'strength', 'barbell',    'intermediate', (select id from m where slug='triceps'),    'Lower bar to forehead, extend triceps.'),
    ('wrist-curl',             'Wrist Curl',                'strength', 'dumbbell',   'beginner',     (select id from m where slug='forearms'),   'Small ROM curl for forearms.'),
    ('back-squat',             'Back Squat',                'strength', 'barbell',    'intermediate', (select id from m where slug='quads'),      'Bar on upper back, squat below parallel.'),
    ('front-squat',            'Front Squat',               'strength', 'barbell',    'advanced',     (select id from m where slug='quads'),      'Bar in front rack, squat upright.'),
    ('goblet-squat',           'Goblet Squat',              'strength', 'dumbbell',   'beginner',     (select id from m where slug='quads'),      'Hold dumbbell at chest, squat.'),
    ('leg-press',              'Leg Press',                 'strength', 'machine',    'beginner',     (select id from m where slug='quads'),      'Press platform, control descent.'),
    ('lunge',                  'Walking Lunge',             'strength', 'dumbbell',   'beginner',     (select id from m where slug='quads'),      'Alternate legs, knee tracks over toe.'),
    ('bulgarian-split-squat',  'Bulgarian Split Squat',     'strength', 'dumbbell',   'intermediate', (select id from m where slug='quads'),      'Rear foot elevated, drop back knee.'),
    ('leg-extension',          'Leg Extension',             'strength', 'machine',    'beginner',     (select id from m where slug='quads'),      'Extend knees to lock out.'),
    ('leg-curl',               'Leg Curl',                  'strength', 'machine',    'beginner',     (select id from m where slug='hamstrings'), 'Curl heels to glutes.'),
    ('hip-thrust',             'Hip Thrust',                'strength', 'barbell',    'intermediate', (select id from m where slug='glutes'),     'Drive hips up, squeeze glutes at top.'),
    ('glute-bridge',           'Glute Bridge',              'strength', 'bodyweight', 'beginner',     (select id from m where slug='glutes'),     'Bridge hips off floor.'),
    ('standing-calf-raise',    'Standing Calf Raise',       'strength', 'machine',    'beginner',     (select id from m where slug='calves'),     'Full stretch and full extension.'),
    ('seated-calf-raise',      'Seated Calf Raise',         'strength', 'machine',    'beginner',     (select id from m where slug='calves'),     'Bent-knee variation for soleus.'),
    ('crunch',                 'Crunch',                    'strength', 'bodyweight', 'beginner',     (select id from m where slug='abs'),        'Curl shoulders off floor.'),
    ('hanging-leg-raise',      'Hanging Leg Raise',         'strength', 'bodyweight', 'intermediate', (select id from m where slug='abs'),        'Raise legs while hanging.'),
    ('plank',                  'Plank',                     'strength', 'bodyweight', 'beginner',     (select id from m where slug='abs'),        'Hold rigid position on forearms.'),
    ('russian-twist',          'Russian Twist',             'strength', 'bodyweight', 'beginner',     (select id from m where slug='obliques'),   'Rotate torso side to side, feet up.'),
    ('side-plank',             'Side Plank',                'strength', 'bodyweight', 'beginner',     (select id from m where slug='obliques'),   'Hold side position on forearm.'),
    ('back-extension',         'Back Extension',            'strength', 'bodyweight', 'beginner',     (select id from m where slug='lower_back'), 'Hyperextend at hip on GHD.'),
    ('good-morning',           'Good Morning',              'strength', 'barbell',    'intermediate', (select id from m where slug='lower_back'), 'Hinge with bar on upper back.'),
    ('kettlebell-swing',       'Kettlebell Swing',          'plyo',     'kettlebell', 'intermediate', (select id from m where slug='glutes'),     'Hip hinge, snap hips to swing to eye level.'),
    ('box-jump',               'Box Jump',                  'plyo',     'bodyweight', 'intermediate', (select id from m where slug='quads'),      'Explode up onto box, step down.'),
    ('burpee',                 'Burpee',                    'plyo',     'bodyweight', 'beginner',     (select id from m where slug='cardio'),     'Down, plank, jump up.'),
    ('mountain-climber',       'Mountain Climber',          'plyo',     'bodyweight', 'beginner',     (select id from m where slug='cardio'),     'Drive knees in from plank.'),
    ('jump-rope',              'Jump Rope',                 'cardio',   'bodyweight', 'beginner',     (select id from m where slug='cardio'),     'Steady bounce, wrist rotation.'),
    ('rowing-erg',             'Rowing Erg',                'cardio',   'machine',    'beginner',     (select id from m where slug='cardio'),     'Legs, hips, arms; reverse in return.'),
    ('run',                    'Run',                       'cardio',   'bodyweight', 'beginner',     (select id from m where slug='cardio'),     'Steady effort run.'),
    ('bike-erg',               'Bike Erg',                  'cardio',   'machine',    'beginner',     (select id from m where slug='cardio'),     'Pedal steady, adjust resistance.'),
    ('assault-bike',           'Assault Bike Sprint',       'cardio',   'machine',    'intermediate', (select id from m where slug='cardio'),     'All-out effort intervals.')
on conflict (slug) do nothing;
