import { StyleSheet } from "react-native";
import { radius, spacing } from "@/src/theme";
import { staffColors as colors, staffFonts, staffShadow, staffType } from "./staff-theme";

export const consoleStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  header: { minHeight: 64, paddingHorizontal: spacing.lg, flexDirection: "row", alignItems: "center", gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, maxWidth: "100%", backgroundColor: colors.bg },
  headerNarrow: { alignItems: "flex-start", flexWrap: "wrap", paddingVertical: spacing.sm },
  icon: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  titleRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing.sm },
  workspace: { paddingHorizontal: spacing.sm, paddingVertical: 3, borderRadius: radius.sm, backgroundColor: colors.surface3, borderWidth: 1, borderColor: colors.borderStrong },
  workspaceText: { color: colors.textMuted, fontFamily: staffFonts.text, fontSize: 10, fontWeight: "600", letterSpacing: 0.6 },
  headerTitle: { ...staffType.section, fontSize: 22 },
  headerMeta: { ...staffType.meta, marginTop: 2, flexShrink: 1 },
  tabs: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: spacing.lg, paddingVertical: spacing.md, gap: spacing.sm, maxWidth: "100%" },
  tab: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: "transparent", borderRadius: radius.sm, backgroundColor: "transparent" },
  tabActive: { borderColor: colors.brand, backgroundColor: colors.surface3 },
  tabText: { ...staffType.nav, color: colors.textMuted },
  tabTextActive: { color: colors.brand },
  badge: { minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 5, backgroundColor: "#9B1C1C", alignItems: "center", justifyContent: "center" },
  badgeText: { color: colors.text, fontSize: 10, fontWeight: "900" },
  scroll: { padding: spacing.lg, paddingBottom: spacing.xxxl, gap: spacing.sm, width: "100%", maxWidth: 1080, alignSelf: "center" },
  section: { ...staffType.section, marginTop: spacing.lg },
  hint: { ...staffType.meta, marginTop: spacing.sm },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  metric: { minWidth: 104, flexGrow: 1, padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surfaceRaised },
  metricValue: { color: colors.text, fontFamily: staffFonts.display, fontSize: 28, lineHeight: 32, fontVariant: ["tabular-nums"] },
  metricLabel: { ...staffType.meta, marginTop: 2 },
  metricHint: { color: colors.textDim, fontSize: 10, lineHeight: 14, marginTop: 4 },
  card: { padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, gap: 6, marginTop: spacing.sm, backgroundColor: colors.surface, maxWidth: "100%" },
  cardHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm, flexWrap: "wrap" },
  tag: { color: colors.error, fontSize: 10, fontWeight: "900", letterSpacing: 1 },
  time: { color: colors.textDim, fontSize: 11 },
  meta: { ...staffType.meta },
  snapshot: { color: colors.text, fontStyle: "italic", lineHeight: 20 },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.sm },
  action: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised },
  actionText: { color: colors.text, fontFamily: staffFonts.text, fontSize: 12, fontWeight: "600", letterSpacing: 0.4 },
  disabled: { opacity: 0.4 },
  link: { color: colors.text, fontSize: 12, fontWeight: "800", marginTop: spacing.sm },
  input: { minHeight: 44, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.sm, color: colors.text, backgroundColor: colors.bg, fontFamily: staffFonts.text, marginBottom: spacing.sm, maxWidth: "100%" },
  replyInput: { minHeight: 88, paddingVertical: spacing.sm, textAlignVertical: "top" },
  searchRow: { flexDirection: "row", gap: spacing.sm, alignItems: "center", maxWidth: "100%" },
  searchBtn: { width: 44, height: 44, borderRadius: radius.sm, backgroundColor: colors.surfaceRaised, alignItems: "center", justifyContent: "center" },
  filters: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginVertical: spacing.sm, maxWidth: "100%" },
  chip: { minHeight: 32, paddingHorizontal: spacing.md, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, justifyContent: "center" },
  chipActive: { borderColor: colors.text, backgroundColor: colors.surfaceRaised },
  chipText: { color: colors.textMuted, fontSize: 10, fontWeight: "900" },
  chipTextActive: { color: colors.text },
  row: { minHeight: 60, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border, maxWidth: "100%" },
  name: { color: colors.text, fontFamily: staffFonts.text, fontWeight: "600" },
  staffTag: { backgroundColor: colors.surfaceRaised, paddingHorizontal: 6, paddingVertical: 2, borderRadius: radius.sm, flexShrink: 1 },
  staffTagText: { color: colors.text, fontSize: 9, fontWeight: "900" },
  suspendedTag: { backgroundColor: colors.error, paddingHorizontal: 6, paddingVertical: 2, borderRadius: radius.sm },
  suspendedTagText: { color: colors.text, fontSize: 9, fontWeight: "900" },
  suspendedNote: { color: colors.error, fontSize: 12, marginTop: 4 },
  note: { paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: colors.border },
  noteText: { color: colors.text, lineHeight: 19 },
  auditRow: { paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border, gap: 2 },
  auditAction: { color: colors.text, fontSize: 12, fontWeight: "900" },
  errorBox: { padding: spacing.md, borderWidth: 1, borderColor: colors.error, borderRadius: radius.sm, gap: 6 },
  error: { color: colors.error },
  retry: { color: colors.text, fontWeight: "900" },
  locked: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing.xl, gap: spacing.md },
  lockedText: { color: colors.textMuted, textAlign: "center" },
  primary: { minHeight: 44, paddingHorizontal: spacing.xl, borderRadius: radius.sm, backgroundColor: colors.brand, alignItems: "center", justifyContent: "center" },
  primaryText: { fontFamily: staffFonts.text, fontSize: 13, fontWeight: "600", letterSpacing: 0.4, color: colors.brandOn },
  overdue: { borderColor: colors.error, backgroundColor: colors.errorWash },
  dialog: { marginTop: spacing.sm, padding: spacing.md, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.md, backgroundColor: colors.surfaceRaised, gap: spacing.sm, maxWidth: "100%", ...staffShadow },
  partial: { color: colors.warning, fontSize: 12, fontWeight: "800" },
});
